import { Equipment } from './app/shared/models/Equipment';

export const sample_equipments: Equipment[] = [
    {
        id: '1',
        name: 'Powder Extinguisher 1 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 1 ק״ג.jpg',
        tags: ['Home'],
    }
    ,
    {
        id: '2',
        name: 'Powder Extinguisher 2 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 2 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '3',
        name: 'Powder Extinguisher 3 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 3 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '4',
        name: 'Powder Extinguisher 6 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 6 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '5',
        name: 'Halo-Carbon Extinguisher 1 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 1 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '6',
        name: 'Halo-Carbon Extinguisher 3 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 3 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '7',
        name: 'Halo-Carbon Extinguisher 6 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 6 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '8',
        name: 'Foam Fire Extinguisher 9 Liter',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש קצף 9 ליטר.jpg',
        tags: ['Home'],
    },
    {
        id: '9',
        name: 'Foam Fire Extinguisher 0.5 Liter',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 0.5 ק״ג.jpg',
        tags: ['Home'],
    },
    {
        id: '10',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Kitchens',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ליטר ייעודי למטבחים.jpg',
        tags: ['Home'],
    },
    {
        id: '11',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Kitchens',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ליטר למטבחים.jpg',
        tags: ['Home'],
    },
    {
        id: '12',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Lihium Batteries',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ק״ג לכיבוי סוללות ליתיום.jpg',
        tags: ['Home'],
    }]
