import { Equipment } from './app/shared/models/Equipment';
import { Tag } from './app/shared/models/Tag';

export const sample_equipments: Equipment[] = [
    {
        id: '1',
        name: 'Powder Extinguisher 1 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 1 ק״ג.jpg',
        tags: ["Houses & Buildings", 'Powder', '1 Kg', 'Cars & Trucks'],
    }
    ,
    {
        id: '2',
        name: 'Powder Extinguisher 2 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 2 ק״ג.jpg',
        tags: ["Houses & Buildings", 'Powder', '2 Kg', 'Cars & Trucks'],
    },
    {
        id: '3',
        name: 'Powder Extinguisher 3 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 3 ק״ג.jpg',
        tags: ["Houses & Buildings", 'Powder', '3 Kg', 'Cars & Trucks'],
    },
    {
        id: '4',
        name: 'Powder Extinguisher 6 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף אבקה 6 ק״ג.jpg',
        tags: ["Houses & Buildings", "Office", "Powder", "6 Kg", "Cars & Trucks"],
    },
    {
        id: '5',
        name: 'Halo-Carbon Extinguisher 1 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 1 ק״ג.jpg',
        tags: ["Houses & Buildings", "Halo - Carbon", "Carbon", "1 Kg", "Electornics Devices"],
    },
    {
        id: '6',
        name: 'Halo-Carbon Extinguisher 3 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 3 ק״ג.jpg',
        tags: ["Houses & Buildings", "Halo - Carbon", "Carbon", "3 Kg", "Electornics Devices", "Cars & Trucks"],
    },
    {
        id: '7',
        name: 'Halo-Carbon Extinguisher 6 Kg',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש גז הלוקרבון 6 ק״ג.jpg',
        tags: ["Houses & Buildings", "Halo - Carbon", "Carbon", "6 Kg", "Electornics Devices", "Office"],
    },
    {
        id: '8',
        name: 'Foam Fire Extinguisher 9 Liter',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף כיבוי אש קצף 9 ליטר.jpg',
        tags: ["9 Liter", "Foam", "Factories"],
    },
    {
        id: '9',
        name: 'Foam Fire Extinguisher 0.5 Liter',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 0.5 ק״ג.jpg',
        tags: ["Foam", "0.5 Liter", "Kitchens", "Factories", "Office"],
    },
    {
        id: '10',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Kitchens',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ליטר ייעודי למטבחים.jpg',
        tags: ["Foam", "6 Liter", "Factories", "Kitchens"],
    },
    {
        id: '11',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Kitchens',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ליטר למטבחים.jpg',
        tags: ["Kitchens", "Factories", "6 Liter", "Foam"],
    },
    {
        id: '12',
        name: 'Foam Fire Extinguisher 6 Liter - Exclusive for Lihium Batteries',
        price: 11,
        expirationTime: '5-10',
        favorite: false,
        origins: ['Germany'],
        stars: 4.0,
        imageUrl: 'assets/Equipments/מטף קצף 6 ק״ג לכיבוי סוללות ליתיום.jpg',
        tags: ["Factories", "6 Kg", "6 Liter", "Electornics Devices"],
    }]

export const sample_tags: Tag[] = [
    { name: 'All', count: 12 },
    { name: 'Powder', count: 4 },
    { name: 'Carbon', count: 3 },
    { name: 'Foam', count: 4 },
    { name: 'Kitchens', count: 3 },
    { name: 'Cars & Trucks', count: 5 },
    { name: 'Office', count: 3 },
    { name: 'Factories', count: 5 },
    { name: 'Electornics Devices', count: 4 },
    { name: 'Houses & Buildings', count: 7 },

]
